title: Lars Brestrich  
logo: /assets/img/headshot_larsB.jpg
description: <br>Data Scientist with MSc from St Andrews (Distinction) and 3 years of professional software development experience. Expertise in implementing complex algorithms and analytics solutions, complemented by strong programming skills in Python and C++. <p> <a href="https://www.linkedin.com/in/lars-brestrich/">LinkedIn</a>
theme: jekyll-theme-minimal
